# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 415b23e6d817eb33fa7a936be44fbfdd08790d972da2f07f94a73388d92f861a570b6b1cd5438dda9b097c3d79102d5962590df3fc0fd1ca5a60a2312041cdfa

test:
  secret_key_base: 565574e4fad542876cd861684807422e78e2ef524211d3a2a094c014c441384b3a3d0a384a66742291e8c1178abf2c519317fa39547b5c6644ed51ca38a57aad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
